config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  get 'about', to: 'pages#about', as: :about
  get 'contact', to: 'pages#contact', as: :contact
  get 'blog', to: 'pages#blog', as: :blog
    get 'decoration', to: 'pages#decoration', as: :decoration
      get 'tips', to: 'pages#tips', as: :tips
        get 'catalogues', to: 'pages#catalogues', as: :catalogues

  resource :user, only: [:edit, :update]

  resources :artisans, only: [:index, :show] do
    resources :prestations, only: [:create]
  end

  resources :projects

  resources :prestations, only: [:show, :update] do
    member do
      post "accept"
      post "decline"
    end
    resources :messages, only: [:create]
  end

  namespace :me_artisans do
    resources :prestations, only: [:index, :edit, :update]
  end
  mount ActionCable.server => "/cable"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" style="background-color: #545d7e" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-success alert-dismissible" style="background-color: #545d7e" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light Regular shadow" style="background: linear-gradient(-180deg, #FAD961 0%, #F5A623 100%);">
  <a class="navbar-brand" href="/"><%= image_tag "me-makers.gif", height: 50 %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <!-- Artisan -->
      <% if current_user.nil?  %>
        <li class="nav-item" style="margin-top: 20px; margin-bottom: 10px">
          <i class="fas fa-sign-in-alt" style="color: rgba(0, 0, 0, .5); margin-right: 10px;"></i>
          <%= link_to 'Connexion', new_user_session_path, class:"nav-link d-inline" %>
        </li>
      <% elsif current_user.artisan %>
        <li class="nav-item" style="margin-top: 20px; margin-bottom: 10px">
          <i class="fas fa-user-alt" style="color: rgba(0, 0, 0, .5); margin-right: 10px;"></i>
          <%= link_to "Mon profil", edit_user_path, class:"nav-link d-inline" %>
        </li>
        <li class="nav-item" style="margin-bottom: 10px">
          <i class="fas fa-file-alt" style="color: rgba(0, 0, 0, .5); margin-right: 14px;"></i>
          <%= link_to "Mes devis", me_artisans_prestations_path, class:"nav-link d-inline" %>
        </li>
        </li>
        <li class="nav-item">
          <i class="fas fa-sign-out-alt" style="color: rgba(0, 0, 0, .5); margin-right: 10px;"></i>
          <%= link_to 'Deconnexion', destroy_user_session_path, class:"nav-link d-inline", method: :delete %>
        </li>
      <!-- User -->
      <% else %>
        <li class="nav-item" style="margin-top: 20px; margin-bottom: 10px">
          <i class="fas fa-user-alt" style="color: rgba(0, 0, 0, .5); margin-right: 10px;"></i>
          <%= link_to "Mon profil", edit_user_path, class:"nav-link d-inline" %>
        </li>
        <li class="nav-item" style="margin-bottom: 10px">
          <i class="fas fa-toolbox" style="color: rgba(0, 0, 0, .5); margin-right: 10px;"></i>
          <%= link_to "Mes projets", projects_path, class:"nav-link d-inline" %>
        </li>
        <li class="nav-item" style="margin-bottom: 10px">
          <i class="fas fa-plus-square" style="color: rgba(0, 0, 0, .5); margin-right: 10px;"></i>
          <%= link_to "Créer mon projet", new_project_path, class:"nav-link d-inline" %>
        </li>
        <li class="nav-item" style="margin-top: 8px">
          <%= form_tag artisans_path, method: :get do %>
            <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Choisissez une catégorie ( ex: peintre... )"
            %>
            <%= submit_tag "Rechercher", class:"btn btn-outline-secondary my-2 my-sm-0 btn-block" %>
          <% end %>
        </li>
        <li class="nav-item">
          <i class="fas fa-sign-out-alt" style="color: rgba(0, 0, 0, .5); margin-right: 10px;"></i>
          <%= link_to 'Deconnexion', destroy_user_session_path, class:"nav-link d-inline", method: :delete %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_rating.html.erb
<% unless artisan.prestations.where(state: "done").empty? %>
  <% average = prestation_rating(artisan.prestations.where(state: "done")) %>
  <% average.times do  %>
    <span style="color: #ffc107; font-size: 15px"><i class="fas fa-star"></i></span>
  <% end %>
  <% (5 - average).times do %>
    <span style="color: #ffc107; font-size: 15px"><i class="far fa-star"></i></span>
  <% end %>
<% end %>

app/views/shared/_review.html.erb
<h1 class="top-title">Avis</h1>

  <div class="card" style="margin-bottom: 100px; margin-top: 20px; background: linear-gradient(-180deg, #FAD961 0%, #F5A623 100%)">
    <div class="card-body">
      <% @prestations.each do |prestation| %>
        <% if prestation.review.present? %>
          <h4><%= User.find(prestation.project.user_id).first_name %> <%= User.find(prestation.project.user_id).last_name %></h4>
          <% if prestation.rating.present? %>
            <% prestation.rating.times do  %>
              <span class="fas fa-star" style="color: black; font-size: 15px"></span>
            <% end %>
            <% (5 - prestation.rating).times do %>
              <span class="fas fa-star" style="color: white; font-size: 15px"></span>
            <% end %>
          <% end %>
          <p class="media-comment">
            <%= prestation.review %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/shared/_sharebutton.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-light border-0 float-right" style="color: #F5A623; background-color: #ffffff; padding-top: 0px; padding-bottom: 0px" data-toggle="modal" data-target="#exampleModal">
<i class="fas fa-share float-right" style="margin-right: 10px"></i>
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Partager sur:</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

       <!--  buttons -->

<style type="text/css">
#my_centered_buttons { display: flex; justify-content: center; }
</style>

<div class="a2a_kit a2a_kit_size_32 a2a_default_style" id="my_centered_buttons">
    <a class="a2a_button_facebook"></a>
    <a class="a2a_button_twitter"></a>
    <a class="a2a_button_google_plus"></a>
    <a class="a2a_button_pinterest"></a>
    <a class="a2a_dd" href="https://www.addtoany.com/share"></a>
</div>

<script async src="https://static.addtoany.com/menu/page.js"></script>

    <!-- end buttons -->


      </div>
    </div>
  </div>
</div>