config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  get 'about', to: 'pages#about', as: :about
  get 'contact', to: 'pages#contact', as: :contact
  get 'blog', to: 'pages#blog', as: :blog
    get 'decoration', to: 'pages#decoration', as: :decoration
      get 'tips', to: 'pages#tips', as: :tips
        get 'catalogues', to: 'pages#catalogues', as: :catalogues

  resource :user, only: [:edit, :update]

  resources :artisans, only: [:index, :show] do
    resources :prestations, only: [:create]
  end

  resources :projects

  resources :prestations, only: [:show, :update] do
    member do
      post "accept"
      post "decline"
    end
    resources :messages, only: [:create]
  end

  namespace :me_artisans do
    resources :prestations, only: [:index, :edit, :update]
  end
  mount ActionCable.server => "/cable"
end

app/views/pages/about.html.erb
<div class="container">
<h1 class="top-title">Qui sommes-nous?</h1>
<p style="text-align: center; color: #535D7E">L'équipe de ME Makers est une équipe de passionnés. Nous avons souhaité mettre nos compétences aux services des particuliers afin de les aider à trouver l'artisan qualifié leur correspondant.</p>



<h1 class="top-title">Notre équipe</h1>
  <div class="row">
    <div class="col-6" style="text-align: center">
      <a href="https://www.linkedin.com/in/sylvain-galtier-61723087/?originalSubdomain=fr" target="_blank">
        <img src="https://kitt.lewagon.com/placeholder/users/SGALT" alt="..." class="img-thumbnail" style="max-height: 150px; max-width: 150px;" >
      </a>
      <p style="color: #535D7E">Sylvain Galtier</p>

    </div>
    <div class="col-6" style="text-align: center">
      <a href="https://www.linkedin.com/in/laura-decroix-713081109/" target="_blank">
        <img src="https://kitt.lewagon.com/placeholder/users/lauradecroix" alt="..." class="img-thumbnail" style="max-height: 150px; max-width: 150px;">
      </a>
      <p style="color: #535D7E">Laura Decroix</p>
    </div>
  </div>
  <div class="row">
    <div class="col-6" style="text-align: center">
      <a href="https://www.linkedin.com/in/remy-sichel-96b131122/" target="_blank">
        <img src="https://kitt.lewagon.com/placeholder/users/Remysichel" alt="..." class="img-thumbnail" style="max-height: 150px; max-width: 150px;">
      </a>
      <p style="color: #535D7E">Remy Sichel</p>
    </div>
    <div class="col-6" style="text-align: center">
      <a href="https://www.linkedin.com/in/j%C3%A9r%C3%A9my-peyrat-226189172/" target="_blank">
        <img src="https://kitt.lewagon.com/placeholder/users/Jerem33320" alt="..." class="img-thumbnail" style="max-height: 150px; max-width: 150px;">
        </a>
      <p style="color: #535D7E">Jeremy Peyrat</p>
    </div>
  </div>
</div>

app/views/pages/blog.html.erb
<div class="container">
  <h1 class="top-title">Notre blog</h1>
    <ul class="nav nav-tabs" style="margin-bottom: 20px">
    <li class="nav-item">
      <%= link_to 'Décoration', decoration_path, class:"nav-link active"%>
    </li>
    <li class="nav-item">
      <%= link_to 'Tips', tips_path, class:"nav-link"%>
    </li>
    <li class="nav-item">
      <%= link_to 'Catalogues', catalogues_path, class:"nav-link"%>
    </li>
  </ul>
</div>

app/views/pages/catalogues.html.erb
<div class="container">
  <h1 class="top-title">Notre blog</h1>
    <ul class="nav nav-tabs" style="margin-bottom: 20px">
    <li class="nav-item">
      <%= link_to 'Déco', decoration_path, class:"nav-link"%>
    </li>
    <li class="nav-item">
      <%= link_to 'Tips', tips_path, class:"nav-link"%>
    </li>
    <li class="nav-item">
      <%= link_to 'Catalogues', catalogues_path, class:"nav-link active"%>
    </li>
  </ul>

  <div class="card">

    <img class="card-img-top" src="http://aikea.by/blog/i/2017/09/IKEA-2018.jpg?$p=hi-w386?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940/100px180/" alt="Card image cap">

    <div class="card-body" style="margin-bottom: 20px">
      <h5 class="card-title">Découvrir le catalogue Ikea</h5>
      <p class="card-text">Un catalogue à feuilleter comme un e-book avec des nouveautés, de l'inspiration et des intérieurs reflétant la diversité de nos modes de vie.</p>
      <a href="https://onlinecatalogue.ikea.com/FR/fr/IKEA_Catalogue/?index&_ga=2.157860152.300565018.1543234304-1322900955.1543234304#/" class="btn btn-light btn-block" target="_blank">Lire</a>
    </div>


  <div class="card">
    <img class="card-img-top" src="https://media.conforama.fr/medias/webmaster/catalogues/2018-conforama_fr-0035-noel_xAWsn474/pages/page-1.jpg?auto=compress&cs=tinysrgb&dpr=2&h=350?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940/100px180/" alt="Card image cap">
    <div class="card-body" style="margin-bottom: 20px">
      <h5 class="card-title">Découvrir le catalogue Conforama</h5>
      <p class="card-text">Un catalogue à feuilleter comme un e-book avec des nouveautés, de l'inspiration et des intérieurs reflétant la diversité de nos modes de vie.</p>
      <a href="https://media.conforama.fr/medias/webmaster/catalogues/2018-conforama_fr-0035-noel_xAWsn474/" class="btn btn-light btn-block" target="_blank">Lire</a>
    </div>


</div>

app/views/pages/contact.html.erb
<div class="container">
  <h1 class="top-title"> Contactez-nous</h1>
<p style="text-align: center; color: #535D7E">Pour toute demande d'informations, n'hésitez pas à nous contacter, nous serons ravis de répondre à vos différentes questions et attentes.</p>



<!------ Include the above in your HEAD tag ---------->

<div class="container contact-form">
            <div class="contact-image" style="text-align: center">
                <img src="http://vf.dsspro.in/images/contact-us.png" style="max-width: 300px; margin-bottom: 20px"/>
            </div>
            <form method="post">
               <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" name="txtName" class="form-control" placeholder="Votre nom *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="txtEmail" class="form-control" placeholder="Votre email *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="txtPhone" class="form-control" placeholder="Your téléphone *" value="" />
                        </div>

                        <div class="form-group">
                            <textarea name="txtMsg" class="form-control" placeholder="Votre message *" style="width: 100%; height: 100px;"></textarea>
                        </div>

                        <div class="form-group">
                            <input type="submit" name="btnSubmit" class="btnContact btn-danger btn-block" value="Envoyer votre message" />
                        </div>
                    </div>

                </div>
            </form>
</div>

</div>

app/views/pages/decoration.html.erb
<div class="container">
  <h1 class="top-title">Notre blog</h1>
    <ul class="nav nav-tabs" style="margin-bottom: 20px">
    <li class="nav-item">
      <%= link_to 'Déco', decoration_path, class:"nav-link active"%>
    </li>
    <li class="nav-item">
      <%= link_to 'Tips', tips_path, class:"nav-link"%>
    </li>
    <li class="nav-item">
      <%= link_to 'Catalogues', catalogues_path, class:"nav-link"%>
    </li>
  </ul>

<div class="card">
  <img class="card-img-top" src="https://s2.lmcdn.fr/multimedia/311501376946/2eea25aba626e/1500x1123-coach-deco.jpg?auto=compress&cs=tinysrgb&dpr=2&h=350?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940/100px180/" alt="Card image cap">
  <div class="card-body" style="margin-bottom: 20px">
    <h5 class="card-title" style="color: #535D7E">Réussir mon projet déco</h5>
    <p class="card-text" style="color: #535D7E">Découvrez les tendances faites pour vous et les astuces de décorateurs pour valoriser au mieux votre pièce. Rapide et facile, la déco de magazine est enfin chez vous !</p>
    <a href="https://www.leroymerlin.fr/v3/p/tous-les-contenus/reussir-mon-projet-deco-l1501373742" target="_blank" class="btn btn-light btn-block">Lire</a>
  </div>

    <img class="card-img-top" src="https://s2.lmcdn.fr/multimedia/281501702399/2d30a5baddce5/comment-choisir-un-tapis-de-decoration/matiere-tapis-de-decoration.jpg?$p=hi-w386?auto=compress&cs=tinysrgb&dpr=2&h=350?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940/100px180/" alt="Card image cap">
  <div class="card-body" style="margin-bottom: 20px">
    <h5 class="card-title" style="color: #535D7E">Comment choisir un tapis de décoration ?</h5>
    <p class="card-text" style="color: #535D7E">Le tapis est un élément important de la décoration. En général, le tapis est choisi en fonction de sa couleur ou de ses motifs, mais d’autres critères sont à prendre en compte : matière, dimensions, forme...</p>
    <a href="https://www.leroymerlin.fr/v3/p/tous-les-contenus/comment-choisir-un-tapis-de-decoration-l1501702720" class="btn btn-light btn-block" target="_blank">Lire</a>
  </div>

<div class="card">
  <img class="card-img-top" src="https://images.pexels.com/photos/1005058/pexels-photo-1005058.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940/100px180/" alt="Card image cap">
  <div class="card-body" style="margin-bottom: 20px">
    <h5 class="card-title" style="color: #535D7E">Dernières tendances déco</h5>
    <p class="card-text" style="color: #535D7E">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" target="_blank" class="btn btn-light btn-block">Lire</a>
  </div>

<div class="card">
  <img class="card-img-top" src="https://images.pexels.com/photos/544112/pexels-photo-544112.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=350?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940/100px180/" alt="Card image cap">
  <div class="card-body" style="margin-bottom: 20px">
    <h5 class="card-title" style="color: #535D7E">Le blanc revient à la mode</h5>
    <p class="card-text" style="color: #535D7E">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" target="_blank" class="btn btn-light btn-block">Lire</a>
  </div>












</div>

app/views/pages/home.html.erb
  <div style="text-align: center; margin-bottom: -100px">
    <img src="https://images.pexels.com/photos/298842/pexels-photo-298842.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=350" class="img-fluid" alt="Responsive image" >
      <p class="caption">ME Makers</p>
      <p><%= link_to "Créez votre projet", new_project_path, class: "bouton-create btn btn-danger"%></p>
  </div>


<div class="container">
<!--   search -->
<div class="search-home">
<%= form_tag artisans_path, method: :get do %>
  <%= text_field_tag :query,
  params[:query],
  class: "form-control",
  placeholder: "Choisissez une catégorie ( ex: peintre... )"
  %>
  <%= submit_tag "Rechercher", class:"btn btn-outline-dark my-2 my-sm-0 btn-block" %>
<% end %>
</div>

<!-- Carousel -->
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="margin-top: 20px; margin-bottom: 20px">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "Etape 111.png", class: "d-block w-100 rounded", alt:"First slide", style:"width: 100%; height: auto;"%>
      <p class="carousel-text">1. Créez votre projet</p>
    </div>
    <div class="carousel-item">
      <%= image_tag "Etape2.png", class: "d-block w-100 rounded", alt:"Second slide", style:"width: 100%; height: auto;"%>
      <p class="carousel-text">2. Sélectionner vos artisans</p>
    </div>
    <div class="carousel-item">
       <%= image_tag "Etapeeeee.png", class: "d-block w-100 rounded", alt:"Third slide", style:"width: 100%; height: 194px"%>
      <p class="carousel-text">3. Réalisez votre projet</p>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<br>

<!-- categories links -->

  <div class="row">
    <div class="col-6 category">
      <p style="color: #535D7E">Spécialités</p>
    </div>
    <div class="col-6 see-all">
    <%= link_to "Tout Voir", artisans_path, class: 'css_class', style: 'color:#F5A623' %>
    </div>
  </div>


 <!--  categories icons-->
<%= render 'shared/categories' %>

 <!--  carte large -->
  <h1 class="top-title" style="margin-top: 60px">Découvrez les derniers artisans :</h1>
  <% @artisans_sample.each do |artisan| %>
    <%= link_to artisan_path(artisan.id) do %>
      <div class="card border-white" style="margin-bottom: 20px">
        <div class="card-body border-white" style="color: #545d7e; text-shadow:none; padding-left: 0px; padding-right: 0px">
            <div class="float-left" style="margin-right: 10px">
              <%= cl_image_tag artisan.photo, class: "rounded-circle", style: "height: 60px; width: 60px"%>
            </div>
            <div style="margin-left: 10px">
              <h5 class="card-title"><%= artisan.specialty %></h5>
              <h6 class="card-title"><%= artisan.first_name %> <%= artisan.last_name %></h6>
              <i class="fas fa-heart float-right"></i>
              <i class="fas fa-share float-right" style="margin-right: 10px; color: #F5A623"></i>
              <%= render 'shared/rating', artisan: artisan %>
            </div>
            <% if artisan.achievements.any? %>
              <%= cl_image_tag artisan.achievements.first.photo, class:"img-thumbnail image-large-card" %>
            <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<div class="footer footer-expand-lg footer-light bg-light Regular shadow" style="background: linear-gradient(-180deg, #FAD961 0%, #F5A623 100%);">
  <nav class="footer">
    <a><%= link_to 'Blog', decoration_path, class:"nav-link"%></a>
    <a><%= link_to 'Contact', contact_path, class:"nav-link"%></a>
    <a><%= link_to 'Qui sommes-nous?', about_path, class:"nav-link"%></a>
  </nav>
</div>

app/views/pages/tips.html.erb
<div class="container">
  <h1 class="top-title">Notre blog</h1>
    <ul class="nav nav-tabs" style="margin-bottom: 20px">
    <li class="nav-item">
      <%= link_to 'Déco', decoration_path, class:"nav-link"%>
    </li>
    <li class="nav-item">
      <%= link_to 'Tips', tips_path, class:"nav-link active"%>
    </li>
    <li class="nav-item">
      <%= link_to 'Catalogues', catalogues_path, class:"nav-link"%>
    </li>
  </ul>

 <div class="card" style="">
  <img class="card-img-top" src="https://s2.lmcdn.fr/multimedia/7e1501658805/29f075b7a8679/comment-choisir-son-radiateur-electrique/photo-introduction.jpg?$p=hi-w386?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940/100px180/" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title" style="color: #535D7E">Comment choisir son radiateur électrique ?</h5>
    <p class="card-text" style="color: #535D7E">Longtemps considéré comme énergivore, le radiateur électrique a bien évolué pour proposer aujourd'hui des solutions adaptées à tous les modes de vie.</p>
    <a href="https://www.leroymerlin.fr/v3/p/tous-les-contenus/comment-choisir-son-radiateur-electrique-l1501658806" class="btn btn-light btn-block" target="_blank">Lire</a>
  </div>

    <div class="card" style="">
  <img class="card-img-top" src="https://s2.lmcdn.fr/multimedia/1f1400905689/1c81954bd1eea/comment-choisir-sa-cheminee/bien-choisir-cheminee-intro.jpg?$p=hi-w386?$p=hi-w386?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940/100px180/" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title" style="color: #535D7E">Comment choisir sa cheminée ?</h5>
    <p class="card-text" style="color: #535D7E">Les cheminées prêtes à poser ressemblent à des cheminées classiques mais leur pose est nettement plus simple. Contre un mur ou au milieu d'une pièce, avec ou sans hotte, encastrées ou autonomes, voici deux familles d'appareils tout en un très pratiques.</p>
    <a href="https://www.leroymerlin.fr/v3/p/tous-les-contenus/comment-choisir-sa-cheminee-l1308220637" target="_blank" class="btn btn-light btn-block">Lire</a>
  </div>


<div class="card" style="">
  <img class="card-img-top" src="https://images.pexels.com/photos/128639/pexels-photo-128639.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940/100px180/" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title" style="color: #535D7E">La tendance hiver : le bois brut</h5>
    <p class="card-text" style="color: #535D7E">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" target="_blank" class="btn btn-light btn-block">Lire</a>
  </div>

  <div class="card" style="">
  <img class="card-img-top" src="https://images.pexels.com/photos/276514/pexels-photo-276514.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940/100px180/" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title" style="color: #535D7E">La brique apparante</h5>
    <p class="card-text" style="color: #535D7E">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-light btn-block">Lire</a>
  </div>



</div>