config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  get 'about', to: 'pages#about', as: :about
  get 'contact', to: 'pages#contact', as: :contact
  get 'blog', to: 'pages#blog', as: :blog
    get 'decoration', to: 'pages#decoration', as: :decoration
      get 'tips', to: 'pages#tips', as: :tips
        get 'catalogues', to: 'pages#catalogues', as: :catalogues

  resource :user, only: [:edit, :update]

  resources :artisans, only: [:index, :show] do
    resources :prestations, only: [:create]
  end

  resources :projects

  resources :prestations, only: [:show, :update] do
    member do
      post "accept"
      post "decline"
    end
    resources :messages, only: [:create]
  end

  namespace :me_artisans do
    resources :prestations, only: [:index, :edit, :update]
  end
  mount ActionCable.server => "/cable"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :prestations, dependent: :destroy

  mount_uploader :photo, PhotoUploader
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.where(user_id: current_user)
  end

  def show
    @prestations = Prestation.where(project_id: @project)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    if @project.save
      redirect_to projects_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @project.update(project_params)
    redirect_to projects_path(@project)
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :date, :photo, :photo_cache)
  end

  def set_project
    @project = Project.find(params[:id])
  end
end

app/views/projects/_form.html.erb
<div>
  <%= simple_form_for @project do |f| %>
    <%= @project.errors.full_messages.join(', ') %>
    <%= f.input :title, label: 'Titre' %>
    <%= f.input :description %>
    <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"} %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.button :submit, class: 'btn btn-danger btn-block' %>
  <% end %>
<br>
  <%= link_to "Accueil", root_path, class: 'btn btn-light btn-block' %>
</div>

app/views/projects/edit.html.erb
<div class="container">
  <h1 class="top-title">Modifier votre projet</h1>

  <%= render "projects/form" %>

</div>

app/views/projects/index.html.erb
<div class="container">
  <h1 class="top-title">Tous mes projets</h1>

    <div style="text-align: center; margin-bottom: 30px">
      <img src="https://pngimage.net/wp-content/uploads/2018/06/homes-png.png" style="max-height: 200px; max-width: -webkit-fill-available">
  </div>

<!--   <% @projects.each do |project| %>
    <div class="card">
      <div class="card-body" style="color: #545d7e; text-shadow:none">
        <div class="row">
          <div class="col-4">
            <%= cl_image_tag project.photo, class: "rounded float-left", style: "height: 100px; width: 100px;" %>
          </div>
          <div class="col-6">
            <h5 class="card-title"><%= link_to project.title, project_path(project),{:style=>'color:#F5A623'} %></h5>
              <p><%= project.description %></p>
            <p class="card-text" style="font-size: 10px"><%= project.date %></p>
            <%= link_to edit_project_path(project) do %>

          </div>
            <div class="col-2" style="background-color: #F5A623" >

                  <i class="fas fa-edit" style="color: white"></i>
              <% end %>
              <%= link_to project_path(project), method: :delete, data: { confirm: "Etes vous sûr ?" } do %>
                <i class="fas fa-trash" style="color: white; margin-right: 10px"></i>
              <% end %>

            </div>
        </div>
      </div>
    </div>
  <% end %> -->

  <% @projects.each do |project| %>
    <div class="row no-gutters" style="margin-bottom: 30px;">
      <div class="col-auto">
        <%= cl_image_tag project.photo, class: "img-fluid", style: "height: 130px; width: 130px;" %>
         <!-- <img src="//placehold.it/120" class="img-fluid" alt=""> -->
      </div>
      <div class="col" style="border-style: solid; border-width:1px; border-color: #f5a62347">
          <div class="card-block px-2">
            <h5 class="card-title" style="margin-top: 10px"><%= link_to project.title, project_path(project),{:style=>'color:#F5A623'} %></h5>
                <p style="color: #535D7E"><%= project.description %></p>
              <p class="card-text" style="font-size: 10px; color: #535D7E"><%= project.date %></p>
          </div>
      </div>
      <div class="col-1" style="background-color: #F5A623; text-align: center; padding-top: 60px">
        <%= link_to edit_project_path(project) do %>
        <i class="fas fa-edit" style="color: white; padding-bottom: 10px"></i>
      <% end %>
      <%= link_to project_path(project), method: :delete, data: { confirm: "Etes vous sûr ?" } do %>
        <i class="fas fa-trash" style="color: white;"></i>
      <% end %>
      </div>
    </div>
  <% end %>

  <%= link_to "Retour", root_path, class: 'btn btn-light btn-block' %>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="btn btn-danger btn-block mt-5" id="chatbot_init" style="align-content: center">Creez votre projet</div>
  <div class="container messages" id="chatbot_div" style="min-height: 400px">
    <%= simple_form_for @project do |f| %>
      <%= @project.errors.full_messages.join(', ') %>
      <span class="d-flex">
        <iframe class="writing d-none" id="writing1" width="100" height="100" src="https://lottiefiles.com/iframe/3317-loading" frameborder="0" allowfullscreen></iframe>
        <p class="message message-content d-none" id="chatbot_intro">
          <%= image_tag 'https://egouvernaire.files.wordpress.com/2015/07/lapinscretinsmeccanoposing_final.jpg?w=560', class: 'avatar mr-2' %>
          Bonjour, je suis Théo le Bricolo pour vous servir
        </p>
      </span>
      <span>
        <iframe class="writing d-none" id="writing2" width="100" height="100" src="https://lottiefiles.com/iframe/3317-loading" frameborder="0" allowfullscreen></iframe>
        <p class="message message-content mt-1 d-none" id="chatbot_intro_1">
          <%= image_tag 'https://egouvernaire.files.wordpress.com/2015/07/lapinscretinsmeccanoposing_final.jpg?w=560', class: 'avatar mr-2' %>
          Je vais vous aider à créer votre projet !!
        </p>
      </span>
      <span>
        <iframe class="writing d-none" id="writing3" width="100" height="100" src="https://lottiefiles.com/iframe/3317-loading" frameborder="0" allowfullscreen></iframe>
        <p class="message message-content mt-1 d-none" id="chatbot_chat_title">
          <%= image_tag 'https://egouvernaire.files.wordpress.com/2015/07/lapinscretinsmeccanoposing_final.jpg?w=560', class: 'avatar mr-2' %>
          Commençons par lui donner un nom :
        </p>
      </span>
      <%= f.input :title, label: false, :input_html => { :class => 'mt-2 d-none', id: 'chatbot_input_title' } %>
      <span>
        <iframe class="writing d-none" id="writing4" width="100" height="100" src="https://lottiefiles.com/iframe/3317-loading" frameborder="0" allowfullscreen></iframe>
        <p class="message message-content mt-1 d-none" id="chatbot_chat_description">
          <%= image_tag 'https://egouvernaire.files.wordpress.com/2015/07/lapinscretinsmeccanoposing_final.jpg?w=560', class: 'avatar mr-2' %>
          Merci !
        </p>
      </span>
      <span>
        <iframe class="writing d-none" id="writing5" width="100" height="100" src="https://lottiefiles.com/iframe/3317-loading" frameborder="0" allowfullscreen></iframe>
        <p class="message message-content mt-1 d-none" id="chatbot_chat_description_1">
          <%= image_tag 'https://egouvernaire.files.wordpress.com/2015/07/lapinscretinsmeccanoposing_final.jpg?w=560', class: 'avatar mr-2' %>
          Maintenant, expliquez nous en détail votre projet (m², pièce, situation, détails....) :
        </p>
      </span>
      <%= f.input :description, label: false, :input_html => { :class => 'mt-2 d-none', id: 'chatbot_input_descrition' } %>
      <span>
        <iframe class="writing d-none" id="writing6" width="100" height="100" src="https://lottiefiles.com/iframe/3317-loading" frameborder="0" allowfullscreen></iframe>
        <p class="message message-content d-none" id="chatbot_chat_date">
          <%= image_tag 'https://egouvernaire.files.wordpress.com/2015/07/lapinscretinsmeccanoposing_final.jpg?w=560', class: 'avatar mr-2' %>
          Merci
        </p>
      </span>
      <span>
        <iframe class="writing d-none" id="writing7" width="100" height="100" src="https://lottiefiles.com/iframe/3317-loading" frameborder="0" allowfullscreen></iframe>
        <p class="message message-content mt-1 d-none" id="chatbot_chat_date_1">
          <%= image_tag 'https://egouvernaire.files.wordpress.com/2015/07/lapinscretinsmeccanoposing_final.jpg?w=560', class: 'avatar mr-2' %>
          Dites nous à quel moment vous souhaitez que les travaux démarre :
        </p>
      </span>
      <%= f.input :date, label: false, as: :string, required: false, :input_html => { :class => 'mt-2 datepicker chatbot_input_date d-none' } %>
      <span>
        <iframe class="writing d-none" id="writing8" width="100" height="100" src="https://lottiefiles.com/iframe/3317-loading" frameborder="0" allowfullscreen></iframe>
        <p class="message message-content mt-1 d-none" id="chatbot_chat_photo">
          <%= image_tag 'https://egouvernaire.files.wordpress.com/2015/07/lapinscretinsmeccanoposing_final.jpg?w=560', class: 'avatar mr-2' %>
          Super !
        </p>
      </span>
      <span>
        <iframe class="writing d-none" id="writing9" width="100" height="100" src="https://lottiefiles.com/iframe/3317-loading" frameborder="0" allowfullscreen></iframe>
        <p class="message message-content mt-1 d-none" id="chatbot_chat_photo_1">
          <%= image_tag 'https://egouvernaire.files.wordpress.com/2015/07/lapinscretinsmeccanoposing_final.jpg?w=560', class: 'avatar mr-2' %>
          Il ne reste plus qu'une étape !! Prenez une photo du futur chantier pour donner une idée à vos interlocuteurs :
        </p>
      </span>
      <%= f.input :photo, label: false, :input_html => { :class => 'mt-2 d-none', id: 'chatbot_input_photo' } %>
      <%= f.input :photo_cache, as: :hidden %>
      <span>
        <iframe class="writing d-none" id="writing10" width="100" height="100" src="https://lottiefiles.com/iframe/3317-loading" frameborder="0" allowfullscreen></iframe>
        <p class="message message-content mt-1 d-none" id="chatbot_chat_submit">
          <%= image_tag 'https://egouvernaire.files.wordpress.com/2015/07/lapinscretinsmeccanoposing_final.jpg?w=560', class: 'avatar mr-2' %>
          Impec !! :)
        </p>
      </span>
      <span>
        <iframe class="writing d-none" id="writing11" width="100" height="100" src="https://lottiefiles.com/iframe/3317-loading" frameborder="0" allowfullscreen></iframe>
        <p class="message message-content mt-1 d-none" id="chatbot_chat_submit_1">
          <%= image_tag 'https://egouvernaire.files.wordpress.com/2015/07/lapinscretinsmeccanoposing_final.jpg?w=560', class: 'avatar mr-2' %>
          Il ne reste plus qu'à valider tout ça avec un dernier click !!
        </p>
      </span>
      <p class="d-none" id="chatbot_submit">
        <%= f.button :submit, 'Créer', class: 'mt-2 btn btn-danger btn-block' %>
      </p>
    <% end %>
  </div>

  <%= link_to "Accueil", root_path, class: 'btn btn-light btn-block mt-3' %>
</div>

app/views/projects/show.html.erb
<div class="container">

  <h1 class="top-title"><%= @project.title %></h1>

<!-- image -->
  <div class="text-center">
    <%= cl_image_tag @project.photo, class: "img-fluid rounded", style: "height: 300px; width: 300px;" %>
    <br>
    <br>
    <h5>Description</h5>
    <p><%= @project.description %></p>
  </div>



<!-- search -->
<h1 class="top-title" style="margin-top: 50px">Trouvez un artisan</h1>
  <div class="search-home" style="margin-bottom: 60px">
    <%= form_tag artisans_path, method: :get do %>
      <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Choisissez une catégorie ( ex: peintre... )"
      %>
      <%= submit_tag "Rechercher", class:"btn btn-outline-dark my-2 my-sm-0 btn-block" %>
    <% end %>
  </div>

<!-- devis -->
<!--   <div class="devis">
    <h5 class="text-center">Devis</h5>
    <% @prestations.each do |prestation| %>
      <div class="card" style="margin-bottom: 30px; background: linear-gradient(-180deg, #FAD961 0%, #F5A623 100%)">
        <div class="card-body" style="color: #545d7e; text-shadow:none">
          <div class="row">
            <div class="col-4">
              <%= cl_image_tag prestation.artisan.photo, class: "rounded float-left", style: "height: 100px; width: 100px"%>
            </div>
            <div class="col-8 prestation-card">
              <h5 class="card-title"><%= link_to prestation.title, prestation_path(prestation) %></h5>
                <p>
                <a class="btn btn-light btn-sm" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                  Show description
                </a>
              </p>
              <div class="collapse" id="collapseExample">
                <div class="card card-body"><%= prestation.description %></div>
              </div>
              <p class="card-text"><%= prestation.artisan.first_name %> <%= prestation.artisan.last_name %></p>
              <div class="prestation-card-actions">
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div> -->

<h1 class="top-title">Devis</h1>

<% @prestations.each do |prestation| %>
    <div class="row no-gutters" style="margin-bottom: 30px;">
      <div class="col-auto">
        <%= cl_image_tag prestation.artisan.photo, class: "img-fluid", style: "height: 150px; width: 130px;" %>

      </div>
      <div class="col" style="border-style: solid; border-width:1px; border-color: #f5a62347">
          <div class="card-block px-2" style="padding-top: 10px;">
            <h5 class="card-title"><%= link_to prestation.title, prestation_path(prestation), {:style=>'color:#F5A623',} %></h5>
                <p style="color: #535D7E"><%= prestation.description %></p>
                <p style="color: #535D7E"><%= prestation.artisan.first_name %> <%= prestation.artisan.last_name %></p>
          </div>
      </div>
      <div class="col-1 prestation-card-actions" style="background-color: #F5A623; text-align: center; padding-top: 80px">
        <% if prestation.booked? %>
          <i class="fas fa-thumbs-up booked" id="thumb-<%= prestation.id %>"></i>
        <% else %>
          <%= link_to accept_prestation_path(prestation), method: :post, remote: true do %>
            <i class="fas fa-thumbs-up" id="thumb-<%= prestation.id %>"></i>
          <% end %>
        <% end %>
        <% if prestation.declined? %>
          <i class="fas fa-times declined" id="cross-<%= prestation.id %>"></i>
        <% else %>
          <%= link_to decline_prestation_path(prestation), method: :post, remote: true do %>
            <i class="fas fa-times" id="cross-<%= prestation.id %>"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>


<!--  boutons -->
  <div class="text-center">
    <%= link_to "Retour", projects_path, class: 'btn btn-light btn-block' %>
  </div>
</div>
<br>