config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  get 'about', to: 'pages#about', as: :about
  get 'contact', to: 'pages#contact', as: :contact
  get 'blog', to: 'pages#blog', as: :blog
    get 'decoration', to: 'pages#decoration', as: :decoration
      get 'tips', to: 'pages#tips', as: :tips
        get 'catalogues', to: 'pages#catalogues', as: :catalogues

  resource :user, only: [:edit, :update]

  resources :artisans, only: [:index, :show] do
    resources :prestations, only: [:create]
  end

  resources :projects

  resources :prestations, only: [:show, :update] do
    member do
      post "accept"
      post "decline"
    end
    resources :messages, only: [:create]
  end

  namespace :me_artisans do
    resources :prestations, only: [:index, :edit, :update]
  end
  mount ActionCable.server => "/cable"
end

app/controllers/artisans_controller.rb
class ArtisansController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    if params[:query].present?
      @artisans = User.search_by_specialty(params[:query])
    else
      @artisans = User.where(artisan: true)
    end
  end

  def show
    @artisan = User.find(params[:id])
    @prestations = Prestation.where(artisan_id: @artisan)
    if @artisan.latitude != nil
      @markers = [{
          lng: @artisan.longitude,
          lat: @artisan.latitude,
          infoWindow: { content: render_to_string(partial: "/artisans/map_window", locals: { artisan: @artisan }) }
        }]
    else
      @markers = [{
          lng: -0.5720551,
          lat: 44.841312,
          infoWindow: { content: render_to_string(partial: "/artisans/map_window", locals: { artisan: @artisan }) }
        }]
    end
  end
end

app/views/artisans/_map_window.html.erb
<h5>Je suis <%= @artisan.first_name %></h5>

app/views/artisans/index.html.erb
<div class="container">
  <h1 class="top-title">Tous nos artisans</h1>

  <div style="text-align: center;">
    <img src="https://www.renovationettravaux.fr/wp-content/uploads/2015/04/Les-artisans-du-b%C3%A2timent.jpg" style="max-height: 200px">
  </div>


  <% @artisans.each do |artisan| %>
    <%= link_to artisan_path(artisan.id) do %>
      <div class="card border-white" style="margin-bottom: 20px">
        <div class="card-body border-white" style="color: #545d7e; text-shadow:none; padding-left: 0px; padding-right: 0px">
          <div class="float-left" style="margin-right: 10px">
            <%= cl_image_tag artisan.photo, class: "rounded-circle", style: "height: 60px; width: 60px" %>
          </div>
          <div style="margin-left: 10px">
            <h5 class="card-title"><%= artisan.specialty %></h5>
            <h6 class="card-title"><%= artisan.first_name %> <%= artisan.last_name %></h6>
            <i class="fas fa-heart float-right"></i>
            <i class="fas fa-share float-right" style="margin-right: 10px"></i>
            <%= render 'shared/rating', artisan: artisan %>
          </div>
          <% if artisan.achievements.any? %>
              <%= cl_image_tag artisan.achievements.first.photo, class:"img-thumbnail image-large-card" %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>




<!--   <div class="row">
    <% @artisans.each do |artisan| %>
      <%= link_to artisan_path(artisan.id) do %>
        <div class="col-xs-12">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
            <div class="card-category">Popular</div>
            <div class="card-description">
              <h2><%= artisan.first_name %><%= artisan.last_name %></h2>
              <h3><%= artisan.specialty %></h3>
            </div>
            <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
          </div>
        </div>
      <% end %>
    <% end  %>
  </div> -->

app/views/artisans/show.html.erb
<div class="container">
    <h1 class="top-title"><%= @artisan.first_name %> <%= @artisan.last_name %></h1>
    <h4 class="top-title"><%= @artisan.specialty %></h4>




<!-- carousel -->
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <% if @artisan.achievements.any? %>
        <%= cl_image_tag @artisan.achievements.first.photo, class: "d-block w-100 rounded", style: "max-height: 194px; object-fit: cover", alt: "First slide" %>
      <% end %>
    </div>
    <div class="carousel-item">
      <% if @artisan.achievements.any? %>
        <%= cl_image_tag @artisan.achievements.second.photo, class: "d-block w-100 rounded", style: "max-height: 194px; object-fit: cover", alt: "Second slide" %>
      <% end %>
    </div>
    <div class="carousel-item">
      <% if @artisan.achievements.any? %>
        <%= cl_image_tag @artisan.achievements.last.photo, class: "d-block w-100 rounded", style: "max-height: 194px; object-fit: cover", alt: "Third slide" %>
      <% end %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


  <!-- profil -->
  <div class="card border-white" style="margin-bottom: 50px; margin-top: 20px">
    <div class="card-body" style="color: #545d7e; text-shadow:none">
        <div class="float-left" style="margin-right: 10px">
          <%= cl_image_tag @artisan.photo, alt: "...", class: "rounded-circle", style: "height: 60px; width: 60px" %>
        </div>
        <div style="margin-left: 10px">
          <h5 class="card-title"><%= @artisan.first_name %> <%= @artisan.last_name %></h5>
          <h6><%= @artisan.specialty %></h6>
          <%= render 'shared/rating', artisan: @artisan %>
          <p class="card-text">
            <p>Entreprise: <%= @artisan.company %></p>
            <p>N° SIRET: <%= @artisan.siret %></p>
            <p>Adresse: <%= @artisan.address %></p>
          </p>

          <i class="fas fa-heart float-right"></i>
          <%= render 'shared/sharebutton' %>
        </div>
    </div>
  </div>

  <!-- Map -->
    <div id="map" style="width: 100%; height: 300px; margin-top: 30px" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>


  <!-- Reviews -->
  <%= render "shared/review" %>


  <!-- Menu déroulant -->
  <% if current_user %>
    <div class="dropup fixed-bottom" style="margin-bottom: 10px">
      <button class="btn btn-danger dropdown-toggle btn-lg btn-block" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Choisissez votre projet
      </button>
      <div class="dropdown-menu btn-block" aria-labelledby="dropdownMenuButton">
      <% current_user.projects.each do |project| %>
        <%= button_to project.title, artisan_prestations_path(@artisan, project_id: project.id), method: :post, class: "dropdown-item" %>
      <% end %>
      </div>
    </div>
  <% end %>
</div>